/*
 * task_I2S.h
 *
 * Created: 4/3/2013 12:05:40 AM
 *  Author: Eva
 */ 


#ifndef TASK_I2S_H_
#define TASK_I2S_H_

#define INITIAL_BITRATE 48000
#define INITIAL_BITDEPTH 24

#define PIN_SSC_RX_DATA			AVR32_SSC_RX_DATA_0_2_PIN
#define FUNC_SSC_RX_DATA		AVR32_SSC_RX_DATA_0_2_FUNCTION
#define PIN_SSC_RX_FSYNC		AVR32_SSC_RX_FRAME_SYNC_0_2_PIN
#define FUNC_SSC_RX_FSYNC		AVR32_SSC_RX_FRAME_SYNC_0_2_FUNCTION
#define PIN_SSC_RX_CLOCK		AVR32_SSC_RX_CLOCK_0_1_PIN
#define	FUNC_SSC_RX_CLOCK		AVR32_SSC_RX_CLOCK_0_1_FUNCTION

#define PIN_SSC_TX_DATA			AVR32_SSC_TX_DATA_0_1_PIN
#define FUNC_SSC_TX_DATA		AVR32_SSC_TX_DATA_0_1_FUNCTION
#define PIN_SSC_TX_FSYNC		AVR32_SSC_TX_FRAME_SYNC_0_1_PIN
#define FUNC_SSC_TX_FSYNC		AVR32_SSC_TX_FRAME_SYNC_0_1_FUNCTION
#define PIN_SSC_TX_CLOCK		AVR32_SSC_TX_CLOCK_0_1_PIN
#define	FUNC_SSC_TX_CLOCK		AVR32_SSC_TX_CLOCK_0_1_FUNCTION

extern void task_I2S_init(void);
extern void task_I2S_change_mclk(uint32_t fs);

#endif /* TASK_I2S_H_ */